### PR TITLE
fix: hug lambdas without blocks

### LINKED ISSUE #650: Regression: more builder chaining being off
**Prettier-Java 2.6.0**

**Input:**

2.5.0
```java
      .map(v ->
        v
          .getPreRelease()
          .stream()
          .filter(p -> p.matches("^\\d+-+g\\p{XDigit}{7}$"))
          .findFirst()
          .map(p -> v.withClearedPreRelease().withPreRelease(SNAPSHOT).withBuild(p))
          .orElse(v)

```

**Output:**
2.6.0
```java
      .map(
        v ->
          v
            .getPreRelease()
            .stream()
            .filter(p -> p.matches("^\\d+-+g\\p{XDigit}{7}$"))
            .findFirst()
            .map(p -> v.withClearedPreRelease().withPreRelease(SNAPSHOT).withBuild(p))
            .orElse(v)
```

**Expected behavior:**
[Prettier TS](
https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAEnADYkQDqEATiQCYAUAlPsADpT5f7VwzrVOdOAGcw1HACM4zDt24A6ALYBDAA4MAbvgC8APnxR0ZXTvzaA-PgAKAJQCiAfQBq92wGUAkgHkAcviRzJjl5fGV1Bnc4JU04aiQkSDiwOGDOUPCNbX18b0kAKzhsEQU4AEd0FRIRLQUAcz5nOJE8KGYAGhsHFzcvPxYrTQUAdxwYAAtrXltSOBURGXdfAEFrd0JvABUWQM000LDVDRCD7L0Tg-MLy7CGmCm4GZI5hdl0m64FERheFSU3j6KVA4EjwagMNS6AxqcIwMDjUQMNggAB6bHRbDoAGoALRYuoYthqYAADQAIjg6mMAL7AADs1IAJMimPtAWFgVA6AAxHDUb4A9mZCFQ8wjMbjADCzxUvDoDyeLxkTHFEwVs3mixWaw221V4wAQugQYw1KzrpcFDR7NUZHsLWz5MKzoY4MN8ABZFSxKBRGJxWp3Jr81rMc3vRR3ZgAbg4HGpIHaIAgalw0BEyFAsuoEGG1llCAzKCqwxUAE8M0nJNQVGAANZ8dx-OAAGRwUDgyFQVQWVZr9cbalr7bqyB+6DgSYWShwY+oE6TcAAHmo4jglAgYFVNnEoLKcKIuz3JyAWlA6s8AIroCDwI+2pP5ERL9wjq83u9IbsPkAVW9wKYUyLEB5hxDs4GEOhExAH4VBBEdJQgJRVGQECyGgs8LzgZYYB+KR0Hgaw4jbDt717EBxhgJQSAocYxlEIcUiiKAWlwTQxjLVCwBESsQE0CdPC5Td3HEHBU2WLl3BgMtnjIk81BzBYKBrNRUIU0Q4liaD2wWah7hrOoUK-Y8kyHfk4lQyQVGkEhoN4Co+QAgyjO-cit0kCgcDoCZkAAJiTdAFk2ayi1ck9omkOhIJbFRz0qBpuRoVRcJHVCVAIiBoIU9sYE87zxmQABGXyAAZqWpIA)

```java
    .map(v ->
      v
        .getPreRelease()
        .stream()
        .filter((p) => p.matches("^\\d+-+g\\p{XDigit}{7}$"))
        .findFirst()
        .map((p) => v.withClearedPreRelease().withPreRelease(SNAPSHOT).withBuild(p))
        .orElse(v),
    )
```

oddly, I think that this would be better, but doesn't really match typescript, I find it weird to have `v` by itself on a line

```java
    .map(v ->
      v.getPreRelease()
        .stream()
        .filter((p) => p.matches("^\\d+-+g\\p{XDigit}{7}$"))
        .findFirst()
        .map((p) => v.withClearedPreRelease().withPreRelease(SNAPSHOT).withBuild(p))
        .orElse(v),
    )
```

Here's the complete method (as per 2.6.0), I line break at 120
```java
 public Semver getMaven() {
    return describe()
      .map(v -> null == v ? PRE_VERSION : v)
      .map(Semver::coerce)
      .map(v -> Objects.equals(v.getVersion(), PRE_VERSION) ? v.withPreRelease(SNAPSHOT) : v)
      .map(
        v ->
          v
            .getPreRelease()
            .stream()
            .filter(p -> p.matches("^\\d+-+g\\p{XDigit}{7}$"))
            .findFirst()
            .map(p -> v.withClearedPreRelease().withPreRelease(SNAPSHOT).withBuild(p))
            .orElse(v)
      )
      .map(v -> new MavenSemver(v.getVersion()))
      .get();
  }
```

### PR DESCRIPTION
**Pull request by jtkiesel**
## What changed with this PR:

Argument "hugging" is now aligned much more closely with Prettier JavaScript. Specifically, lambdas without blocks are "huggable" again.

### Input
```java
class T {

  public Semver getMaven() {
    return describe()
      .map(v -> null == v ? PRE_VERSION : v)
      .map(Semver::coerce)
      .map(v -> Objects.equals(v.getVersion(), PRE_VERSION) ? v.withPreRelease(SNAPSHOT) : v)
      .map(
        v ->
          v
            .getPreRelease()
            .stream()
            .filter(p -> p.matches("^\\d+-+g\\p{XDigit}{7}$"))
            .findFirst()
            .map(p -> v.withClearedPreRelease().withPreRelease(SNAPSHOT).withBuild(p))
            .orElse(v)
      )
      .map(v -> new MavenSemver(v.getVersion()))
      .get();
  }

  void t() {
    aaaaaaaaaaaaaaaaaaaaaaaa((bbbbbbbbbbbbbbbbbbbbbbbb, cccccccccccccccccccccccc, dddddddddddddddddddddddd) -> eeeeeeeeeeeeeeeeeeeeeeee.ffffffffffffffffffffffff());

    a.b(c -> d -> eeeeeeeeee.ffffffffff(gggggggggg, hhhhhhhhhh, iiiiiiiiii, jjjjjjjjjj, kkkkkkkkkk));

    a.b(c -> d && eeeeeeeeee.ffffffffff() ? g && hhhhhhhhhh.iiiiiiiiii() : j && kkkkkkkkkk.llllllllll());

    a.b(c -> d && eeeeeeeeee.ffffffffff(gggggggggg, hhhhhhhhhh, iiiiiiiiii, jjjjjjjjjj, kkkkkkkkkk) > 0);

    a.b(c, (c0, c1) -> d && eeeeeeeeee.ffffffffff(gggggggggg, hhhhhhhhhh, iiiiiiiiii, jjjjjjjjjj, kkkkkkkkkk) > 0);

    a.b(c -> eeeeeeeeee.ffffffffff(gggggggggg, hhhhhhhhhh, iiiiiiiiii, jjjjjjjjjj, kkkkkkkkkk) > 0);

    a.b(c, (c0, c1) -> eeeeeeeeee.ffffffffff(gggggggggg, hhhhhhhhhh, iiiiiiiiii, jjjjjjjjjj, kkkkkkkkkk) > 0);

    a.b(c -> d && eeeeeeeeee.ffffffffff(gggggggggg, hhhhhhhhhh, iiiiiiiiii, jjjjjjjjjj, kkkkkkkkkk));

    a.b(c, (c0, c1) -> d && eeeeeeeeee.ffffffffff(gggggggggg, hhhhhhhhhh, iiiiiiiiii, jjjjjjjjjj, kkkkkkkkkk));

    a.b(c -> eeeeeeeeee.ffffffffff(gggggggggg, hhhhhhhhhh, iiiiiiiiii, jjjjjjjjjj, kkkkkkkkkk));

    a.b(c -> {
      eeeeeeeeee.ffffffffff(gggggggggg, hhhhhhhhhh, iiiiiiiiii, jjjjjjjjjj, kkkkkkkkkk);
    });

    a.b((c0, c1) -> eeeeeeeeee.ffffffffff(gggggggggg, hhhhhhhhhh, iiiiiiiiii, jjjjjjjjjj, kkkkkkkkkk));

    a.b(c, (c0, c1) -> eeeeeeeeee.ffffffffff(gggggggggg, hhhhhhhhhh, iiiiiiiiii, jjjjjjjjjj, kkkkkkkkkk));
  }
}
```

### Output
```java
class T {

  public Semver getMaven() {
    return describe()
      .map(v -> null == v ? PRE_VERSION : v)
      .map(Semver::coerce)
      .map(v ->
        Objects.equals(v.getVersion(), PRE_VERSION)
          ? v.withPreRelease(SNAPSHOT)
          : v
      )
      .map(v ->
        v
          .getPreRelease()
          .stream()
          .filter(p -> p.matches("^\\d+-+g\\p{XDigit}{7}$"))
          .findFirst()
          .map(p ->
            v.withClearedPreRelease().withPreRelease(SNAPSHOT).withBuild(p)
          )
          .orElse(v)
      )
      .map(v -> new MavenSemver(v.getVersion()))
      .get();
  }

  void t() {
    aaaaaaaaaaaaaaaaaaaaaaaa(
      (
        bbbbbbbbbbbbbbbbbbbbbbbb,
        cccccccccccccccccccccccc,
        dddddddddddddddddddddddd
      ) -> eeeeeeeeeeeeeeeeeeeeeeee.ffffffffffffffffffffffff()
    );

    a.b(
      c ->
        d ->
          eeeeeeeeee.ffffffffff(
            gggggggggg,
            hhhhhhhhhh,
            iiiiiiiiii,
            jjjjjjjjjj,
            kkkkkkkkkk
          )
    );

    a.b(c ->
      d && eeeeeeeeee.ffffffffff()
        ? g && hhhhhhhhhh.iiiiiiiiii()
        : j && kkkkkkkkkk.llllllllll()
    );

    a.b(
      c ->
        d &&
        eeeeeeeeee.ffffffffff(
          gggggggggg,
          hhhhhhhhhh,
          iiiiiiiiii,
          jjjjjjjjjj,
          kkkkkkkkkk
        ) >
        0
    );

    a.b(
      c,
      (c0, c1) ->
        d &&
        eeeeeeeeee.ffffffffff(
          gggggggggg,
          hhhhhhhhhh,
          iiiiiiiiii,
          jjjjjjjjjj,
          kkkkkkkkkk
        ) >
        0
    );

    a.b(
      c ->
        eeeeeeeeee.ffffffffff(
          gggggggggg,
          hhhhhhhhhh,
          iiiiiiiiii,
          jjjjjjjjjj,
          kkkkkkkkkk
        ) >
        0
    );

    a.b(
      c,
      (c0, c1) ->
        eeeeeeeeee.ffffffffff(
          gggggggggg,
          hhhhhhhhhh,
          iiiiiiiiii,
          jjjjjjjjjj,
          kkkkkkkkkk
        ) >
        0
    );

    a.b(
      c ->
        d &&
        eeeeeeeeee.ffffffffff(
          gggggggggg,
          hhhhhhhhhh,
          iiiiiiiiii,
          jjjjjjjjjj,
          kkkkkkkkkk
        )
    );

    a.b(
      c,
      (c0, c1) ->
        d &&
        eeeeeeeeee.ffffffffff(
          gggggggggg,
          hhhhhhhhhh,
          iiiiiiiiii,
          jjjjjjjjjj,
          kkkkkkkkkk
        )
    );

    a.b(c ->
      eeeeeeeeee.ffffffffff(
        gggggggggg,
        hhhhhhhhhh,
        iiiiiiiiii,
        jjjjjjjjjj,
        kkkkkkkkkk
      )
    );

    a.b(c -> {
      eeeeeeeeee.ffffffffff(
        gggggggggg,
        hhhhhhhhhh,
        iiiiiiiiii,
        jjjjjjjjjj,
        kkkkkkkkkk
      );
    });

    a.b((c0, c1) ->
      eeeeeeeeee.ffffffffff(
        gggggggggg,
        hhhhhhhhhh,
        iiiiiiiiii,
        jjjjjjjjjj,
        kkkkkkkkkk
      )
    );

    a.b(c, (c0, c1) ->
      eeeeeeeeee.ffffffffff(
        gggggggggg,
        hhhhhhhhhh,
        iiiiiiiiii,
        jjjjjjjjjj,
        kkkkkkkkkk
      )
    );
  }
}
```

## Relative issues or prs:

Closes #650

### CODE REVIEW

File: packages/prettier-plugin-java/src/printers/expressions.ts [hunk 1]
```diff
@@ -119,19 +111,18 @@ export class ExpressionsPrettierVisitor extends BaseCstPrettierPrinter {
...
   lambdaParametersWithBraces(
     ctx: LambdaParametersWithBracesCtx,
-    params?: { shouldBreak?: boolean }
+    params?: { flat?: boolean }
   ) {
     const lambdaParameterList = this.visit(ctx.lambdaParameterList, params);
 
     if (findDeepElementInPartsArray(lambdaParameterList, ",")) {
-      const separator = params?.shouldBreak === false ? "" : softline;
-      const content = putIntoBraces(
```
Comment (clementdessoude) [inline packages/prettier-plugin-java/src/printers/expressions.ts:128]: I think that there is some logic handling comments around braces in the putIntoBraces function: does it still works well if you remove the putIntoBraces method ?

Comment (jtkiesel) [reply packages/prettier-plugin-java/src/printers/expressions.ts:128]: You're very right! This ended up sending me down quite a bit of a rabbit hole.

I realized that, because of the way `putIntoBraces` removes comments and puts them directly into the `Doc` it returns (rather than moving them to another token/node), it meant that certain code paths in which I leveraged the `conditionalGroup` function could result in comments being removed from the code entirely (😱).

I believe that I have now fixed that problem, and have added a bunch of tests for comments around methods and lambdas to ensure I handled all those cases properly.

**Comment by jtkiesel** [comment]
@clementdessoude Apologies for the ping, but just wanted to check in to ask if you could take another look at this, whenever you have the time. Thanks in advance!

**Comment by clementdessoude** [comment]
Hello @jtkiesel ! No worry for the ping, it is totally normal. Would you be able to have a chat (through mail/twitter/linkedin/any media you want) ? I tried to contact you via linkedin a few weeks ago to discuss about the project, but you may have missed it :)
