### PR TITLE
fix: limit TypePattern's VariableDeclaratorList to a single VariableDeclarator

### LINKED ISSUE #733: Formatting fails with unnamed and multiple patterns from inner interface
prettier-plugin-java version: 2.6.7
java version: 24 but will work also above 22

This code leads to errors

```java
public class Fail {

  private Function<ShootResult, ShootResult.Miss> missed() {
    return lastResult -> switch (lastResult) {
      case ShootResult.Miss(int fails) -> new ShootResult.Miss(fails + 1);
      case ShootResult.Many _ ,ShootResult.One _ -> new ShootResult.Miss(0); // crash on this line
             
    };
  }

  private sealed interface ShootResult {
    record One(Pin pin) implements ShootResult {}
    record Many(int number) implements ShootResult {}
    record Miss(int timesInRow) implements ShootResult {}
  }
}
```
`src/main/java/kata/Fail.java: Error: Sad sad panda, parsing errors detected in line: 11, column: 43!
[error] Expecting --> '->' <-- but found --> '.' <--!`

### PR DESCRIPTION
**Pull request by jtkiesel**
## What changed with this PR:

There exists some ambiguity in the parser within comma-separated `TypePattern`s, because `TypePattern` contains a `VariableDeclaratorList`, which is comma-separated `VariableDeclarator`s. The parser cannot currently determine where the `VariableDeclaratorList` ends and the next `TypePattern` begins. This was previously realized in #707, within `ComponentPatternList`, and is now experienced in #733, within `SwitchLabel`.

I realized that the JLS specifically mentions semantic restrictions that make it easy to resolve this ambiguity. From [14.30.1. Kinds of Patterns](https://docs.oracle.com/javase/specs/jls/se24/html/jls-14.html#jls-14.30.1) (emphasis mine):
> The rules for a local variable declared in a type pattern are specified in [§14.4](https://docs.oracle.com/javase/specs/jls/se24/html/jls-14.html#jls-14.4). In addition, all of the following must be true, or a compile-time error occurs:
> * The _LocalVariableType_ in a top level type pattern denotes a reference type (and furthermore is not var).
> * **The _VariableDeclaratorList_ consists of a single _VariableDeclarator_.**
> * The _VariableDeclarator_ has no initializer.
> * The _VariableDeclaratorId_ has no bracket pairs.

As such, this PR limits `TypePattern`'s `VariableDeclaratorList` to a single `VariableDeclarator` in our parser. That change also allowed me to remove the patch that was added in #708, as this fix also resolves the ambiguity for the issue seen in #707.

### Input

```java
public class Fail {

  private Function<ShootResult, ShootResult.Miss> missed() {
    return lastResult -> switch (lastResult) {
      case ShootResult.Miss(int fails) -> new ShootResult.Miss(fails + 1);
      case ShootResult.Many _ ,ShootResult.One _ -> new ShootResult.Miss(0); // crash on this line
             
    };
  }

  private sealed interface ShootResult {
    record One(Pin pin) implements ShootResult {}
    record Many(int number) implements ShootResult {}
    record Miss(int timesInRow) implements ShootResult {}
  }
}
```

### Output

```java
public class Fail {

  private Function<ShootResult, ShootResult.Miss> missed() {
    return lastResult ->
      switch (lastResult) {
        case ShootResult.Miss(int fails) -> new ShootResult.Miss(fails + 1);
        case ShootResult.Many _, ShootResult.One _ -> new ShootResult.Miss(0); // crash on this line
      };
  }

  private sealed interface ShootResult {
    record One(Pin pin) implements ShootResult {}

    record Many(int number) implements ShootResult {}

    record Miss(int timesInRow) implements ShootResult {}
  }
}
```

## Relative issues or prs:

Closes #733

### CODE REVIEW

File: packages/java-parser/src/productions/blocks-and-statements.js [hunk 1]
```diff
@@ -41,12 +41,12 @@ export function defineRules($, t) {
   });
 
   // https://docs.oracle.com/javase/specs/jls/se22/html/jls-14.html#jls-LocalVariableDeclaration
-  $.RULE("localVariableDeclaration", () => {
+  $.RULE("localVariableDeclaration", singleDeclarator => {
```
Comment (clementdessoude) [inline packages/java-parser/src/productions/blocks-and-statements.js:44]: Maybe rename this argument to isSingleDeclarator (in order to emphasize the fact this is a boolean and not confuse it with the actual singleDeclarator node content) ?

**Review by clementdessoude — APPROVED** [review]
Great work ! And well spotted 😀 

Just a small suggestion but we also could merge at is

File: packages/java-parser/src/productions/blocks-and-statements.js (hunk 1 above)
Comment (jtkiesel) [reply packages/java-parser/src/productions/blocks-and-statements.js]: Good idea! Done, and will merge once the tests pass.

**Comment by jtkiesel** [comment]
@lanwen Sorry for the delay. I'd like to get this project to auto-publish new versions of the package for each meaningful commit pushed to main, but for now releases are manual. Thanks for your patience! I've published version [2.6.8](https://github.com/jhipster/prettier-java/releases/tag/prettier-plugin-java%402.6.8), so please give that a try and let me know if you experience any issues!
