### PR TITLE
Fix interfaces user blank lines

### LINKED ISSUE #220: Suggestion: Annotation break line
```
/**
* Spring Data MongoDB repository for the {@link User} entity.
*/
@Repository
private interface UserRepository extends ReactiveMongoRepository<User, String> {
  String USERS_BY_LOGIN_CACHE = "usersByLogin";
  String USERS_BY_EMAIL_CACHE = "usersByEmail";
  Mono<User> findOneByActivationKey(String activationKey);
  Flux<User> findAllByActivatedIsFalseAndActivationKeyIsNotNullAndCreatedDateBefore(Instant dateTime);
  Mono<User> findOneByResetKey(String resetKey);
  @Cacheable(cacheNames = USERS_BY_EMAIL_CACHE)
  Mono<User> findOneByEmailIgnoreCase(String email);
  @Cacheable(cacheNames = USERS_BY_LOGIN_CACHE)
  Mono<User> findOneByLogin(String login);
  Flux<User> findAllByLoginNot(Pageable pageable, String login);
  Mono<Long> countAllByLoginNot(String anonymousUser);
}
```

For better readability, the printer should print:

```
/**
* Spring Data MongoDB repository for the {@link User} entity.
*/
@Repository
private interface UserRepository extends ReactiveMongoRepository<User, String> {
  String USERS_BY_LOGIN_CACHE = "usersByLogin";
  String USERS_BY_EMAIL_CACHE = "usersByEmail";
  Mono<User> findOneByActivationKey(String activationKey);
  Flux<User> findAllByActivatedIsFalseAndActivationKeyIsNotNullAndCreatedDateBefore(Instant dateTime);
  Mono<User> findOneByResetKey(String resetKey);

  @Cacheable(cacheNames = USERS_BY_EMAIL_CACHE)
  Mono<User> findOneByEmailIgnoreCase(String email);

  @Cacheable(cacheNames = USERS_BY_LOGIN_CACHE)
  Mono<User> findOneByLogin(String login);

  Flux<User> findAllByLoginNot(Pageable pageable, String login);
  Mono<Long> countAllByLoginNot(String anonymousUser);
}
```

IMO,
We should be careful of users' blank lines too.

### PR DESCRIPTION
**Pull request by clement26695**
Refactor the way we handle classBody declarations and apply the same logic to interface body declarations.

Fix #220

### CODE REVIEW

File: packages/prettier-plugin-java/src/printers/classes.js [hunk 1]
```diff
@@ -116,27 +116,29 @@ class ClassesPrettierVisitor {
...
-      this.mapVisit(ctx.classBodyDeclaration)
-    );
-    const classBodyDecls = handleClassBodyDeclaration(
-      ctx.classBodyDeclaration,
-      classBodyDeclsVisited
-    );
-
     let content = "";
-    if (classBodyDecls.length !== 0) {
+    if (ctx.classBodyDeclaration !== undefined) {
```
Comment (Shaolans) [inline packages/prettier-plugin-java/src/printers/classes.js]: ``` if (ctx.classBodyDeclaration) {``` ?

Comment (clement26695) [reply packages/prettier-plugin-java/src/printers/classes.js]: it is a bit faster to specify it (otherwise, will test if different from "", [], ....), I think. 

As I don't find that it clarifies the code to remove it, I tend to always specify it
