### PR TITLE
fix: constructor and method receiver parameter

### LINKED ISSUE #607: Fails with receiver parameter (implicit this)
Hi, thank you for this great tool.

Although the receiver (parameter implicit this) is a rarely used syntax, but is valid in java and required when using Checker Framework, [example here](https://checkerframework.org/manual/#underinitialization-examples)

Looking at the parser code I see that it is supported in constructors

Input:
```
class Foo {
    public void test(Foo this) {
        // This fails
    }

    public void test(Foo this, Bar that) {
        // This fails
    }
}
```

Output:
```
[error] Foo.java: Error: Sad sad panda, parsing errors detected in line: 2, column: 26!
[error] Expecting --> '...' <-- but found --> 'this' <--!
[error]         ->compilationUnit
[error]         ->ordinaryCompilationUnit
[error]         ->typeDeclaration
[error]         ->classDeclaration
[error]         ->normalClassDeclaration
[error]         ->classBody
[error]         ->classBodyDeclaration
[error]         ->classMemberDeclaration
[error]         ->methodDeclaration
[error]         ->methodHeader
[error]         ->methodDeclarator
[error]         ->formalParameterList
[error]         ->formalParameter
[error]         ->variableArityParameter
[error]     at Object.parse (<…>/prettier-java-repro/node_modules/java-parser/src/index.js:41:11)
[error]     at Object.parse (<…>/prettier-java-repro/node_modules/prettier-plugin-java/dist/parser.js:4:23)
[error]     at parse (file://<…>/prettier-java-repro/node_modules/prettier/index.mjs:16786:24)
[error]     at async coreFormat (file://<…>/prettier-java-repro/node_modules/prettier/index.mjs:18107:7)
[error]     at async formatWithCursor (file://<…>/prettier-java-repro/node_modules/prettier/index.mjs:18309:14)
[error]     at async formatFiles (file://<…>/prettier-java-repro/node_modules/prettier/internal/cli.mjs:7082:18)
[error]     at async main (file://<…>/prettier-java-repro/node_modules/prettier/internal/cli.mjs:7274:5)
[error]     at async Module.run (file://<…>/prettier-java-repro/node_modules/prettier/internal/cli.mjs:7228:5)
error Command failed with exit code 2.
```

Weirdly I found some mentions of receiver parameter but in the `constructorDeclarator` where it shouldn't be supported

Thanking in advance

### PR DESCRIPTION
**Pull request by jtkiesel**
## What changed with this PR:

Fixes some issues with constructor receiver parameters, and added support for method receiver parameters.

### Input
```java
class Currency {
  Currency(Currency this) {}

  Currency(Currency this, Currency other) {}

  Currency(@AnnotatedUsage Currency this, Currency other) {}

  Currency(@AnnotatedUsage Currency this, String aaaaaaaaaa, String bbbbbbbbbb) {}

  String getCode(Currency this) {}

  int compareTo(Currency this, Currency other) {}

  int compareTo(@AnnotatedUsage Currency this, Currency other) {}

  int compareTo(@AnnotatedUsage Currency this, String aaaaaaaaaa, String bbbbbbbbbb) {}

  class Inner {
    Inner(Currency Currency.this) {}

    String getCode(Currency Currency.this) {}
  }
}
```

### Output
```java
class Currency {

  Currency(Currency this) {}

  Currency(Currency this, Currency other) {}

  Currency(@AnnotatedUsage Currency this, Currency other) {}

  Currency(
    @AnnotatedUsage Currency this,
    String aaaaaaaaaa,
    String bbbbbbbbbb
  ) {}

  String getCode(Currency this) {}

  int compareTo(Currency this, Currency other) {}

  int compareTo(@AnnotatedUsage Currency this, Currency other) {}

  int compareTo(
    @AnnotatedUsage Currency this,
    String aaaaaaaaaa,
    String bbbbbbbbbb
  ) {}

  class Inner {

    Inner(Currency Currency.this) {}

    String getCode(Currency Currency.this) {}
  }
}
```

## Relative issues or prs:

Closes #607

### CODE REVIEW

File: packages/java-parser/src/productions/classes.js [hunk 1]
```diff
@@ -320,13 +320,22 @@ export function defineRules($, t) {
     ]);
   });
 
-  // https://docs.oracle.com/javase/specs/jls/se8/html/jls-8.html#jls-MethodDeclarator
```
Comment (clementdessoude) [inline packages/java-parser/src/productions/classes.js:323]: Quite a bump ! 😆

File: packages/prettier-plugin-java/src/printers/classes.ts [hunk 2]
```diff
@@ -588,15 +592,11 @@ export class ClassesPrettierVisitor extends BaseCstPrettierPrinter {
...
 
-    return rejectAndJoin("", [
-      rejectAndJoin(" ", annotations),
+    return rejectAndJoin(" ", [
+      ...annotations,
       unannType,
-      identifier,
-      ctx.This[0]
+      rejectAndConcat([ctx.Identifier?.[0], ctx.Dot?.[0], ctx.This[0]])
     ]);
```
Comment (clementdessoude) [inline packages/prettier-plugin-java/src/printers/classes.ts:600]: There was not any space before and after the unannType, was it an issue ?

**Review by clementdessoude — COMMENTED** [review]
Just one question, but LGTM !

File: packages/prettier-plugin-java/src/printers/classes.ts (hunk 2 above)
Comment (jtkiesel) [reply packages/prettier-plugin-java/src/printers/classes.ts:600]: It was -- previously, the unannType was squashed up against the annotations (if there were any) and the identifier/`this`. It just so happened that we didn't have any tests for this, and I suppose it's such a rare syntax that the issue wasn't encountered elsewhere.
