### PR TITLE
fix: break long assignments after equals

### LINKED ISSUE #527: Print width not obeyed on assignments
**Prettier-Java 1.6.1**

```sh
# Options:
--print-width 80
--tab-width 4
```

**Input:**

```java
package org.prettier.java;

public class MyReallyLongClassName {

    public void method() {
        MyReallyLongClassName myReallyLongVariableName = new MyReallyLongClassName();
        MyReallyLongClassName myReallyLongVariableName2 = myReallyLongMethodName();
    }

    public MyReallyLongClassName myReallyLongMethodName() {
        return new MyReallyLongClassName();
    }
}
```

**Output:**

```java
package org.prettier.java;

public class MyReallyLongClassName {

    public void method() {
        MyReallyLongClassName myReallyLongVariableName = new MyReallyLongClassName();
        MyReallyLongClassName myReallyLongVariableName2 = myReallyLongMethodName();
    }

    public MyReallyLongClassName myReallyLongMethodName() {
        return new MyReallyLongClassName();
    }
}
```

**Expected behavior:**

```java
package org.prettier.java;

public class MyReallyLongClassName {

    public void method() {
        MyReallyLongClassName myReallyLongVariableName =
            new MyReallyLongClassName();
        MyReallyLongClassName myReallyLongVariableName2 =
            myReallyLongMethodName();
    }

    public MyReallyLongClassName myReallyLongMethodName() {
        return new MyReallyLongClassName();
    }
}
```

I expect lines that exceed the configured print width to be broken after `=`.

This used to be an issue for Prettier with JavaScript as well, see https://github.com/prettier/prettier/issues/2482. However, https://github.com/prettier/prettier/pull/10222 seems to have fixed most of the issues (at least for the two examples I have given, of instantiation and method return value assignment).

### PR DESCRIPTION
**Pull request by jtkiesel**
## What changed with this PR:

Long assignments (i.e. those that previously violated printWidth) of many types now break after equals the way Prettier JavaScript now does.

### Input
```java
class Example {

  void example() {
    Object aParticularlyLongAndObnoxiousNameForIllustrativePurposes = new Object()
      .someMethod();

    Object[] aParticularlyLongAndObnoxiousNameForIllustrativePurposes2 = new Object[] {
      new Object(),
      new Object()
    };

    Object aParticularlyLongAndObnoxiousNameForIllustrativePurposes3 = SomeClass.someStaticMethod();

    Object aParticularlyLongAndObnoxiousNameForIllustrativePurposes = someMethod()
      .anotherMethod();

    Object aParticularlyLongAndObnoxiousNameForIllustrativePurposes = anotherValue !=
      null
      ? anotherValue
      : new Object();
  }
}
```

### Output
```java
class Example {

  void example() {
    Object aParticularlyLongAndObnoxiousNameForIllustrativePurposes =
      new Object().someMethod();

    Object[] aParticularlyLongAndObnoxiousNameForIllustrativePurposes2 =
      new Object[] { new Object(), new Object() };

    Object aParticularlyLongAndObnoxiousNameForIllustrativePurposes3 =
      SomeClass.someStaticMethod();

    Object aParticularlyLongAndObnoxiousNameForIllustrativePurposes =
      someMethod().anotherMethod();

    Object aParticularlyLongAndObnoxiousNameForIllustrativePurposes =
      anotherValue != null ? anotherValue : new Object();
  }
}
```

## Relative issues or prs:

Fix #527

### CODE REVIEW

**Comment by jtkiesel** [comment]
@clementdessoude I don't mean to sound impatient, so I apologize in advanced, I just wanted to make sure that I have done everything I needed to do for this pull request. I'm not sure if there's anything I'm missing, or if anyone else handles pull request reviews/merges. Any chance this could get a (hopefully quick) review?

File: packages/prettier-plugin-java/src/printers/classes.ts [hunk 1]
```diff
@@ -330,10 +330,13 @@ export class ClassesPrettierVisitor extends BaseCstPrettierPrinter {
...
             .ternaryExpression[0].children.QuestionMark !== undefined)
       ) {
-        return rejectAndJoin(" ", [
-          variableDeclaratorId,
-          ctx.Equals[0],
-          variableInitializer
+        const groupId = Symbol("assignment");
+        return group([
+          group(variableDeclaratorId),
+          " =",
```
Comment (clementdessoude) [inline packages/prettier-plugin-java/src/printers/classes.ts:336]: I think that with this implementation, some (oddly placed) comment might disapear. For instance, I think that in one of these two statements, the comment will disapear, as it is attached to the ctx.Equals[0] symbol.

`private Map<Integer, String> genericVariable4 /* comment */= new HashMap<Integer, String>();` or `private Map<Integer, String> genericVariable4 =/* comment */ new HashMap<Integer, String>();`

Can you try to add this test case and check if it is the case ? If the comment disappears, you can try to replace " =" by `" ", ctx.Equals[0],` here and in the three declarations afterwards

**Comment by clementdessoude** [comment]
Once again, I'm so sorry for the very long delay in the response. Thanks for pinging me back again !

I have a small comment, let me know if you can tackle it. Otherwise, I should be able to test it in the evening or tomorrow.

**Comment by jtkiesel** [comment]
No worries at all, I'm sorry if I came off as impatient or rude. Thank you for taking the time to review!

**Comment by clementdessoude** [comment]
Well done ! I had just one doubt I wanted to clear up before merging, but everything looks fine ! Thanks a lot @jtkiesel !
